name: Publish Features

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "features/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Publish features
        uses: devcontainers/action@v1
        with:
          publish-templates: false
          publish-features: true
          base-path-to-features: "./features"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
